# Data Treatment for County-Level COVID-19 Analysis
## Curtis Peterson

This notebook creates a .csv file that combines county-level COVID-19 data from the [covid act now](https://covidactnow.org/?s=27521640) API with 2020 census data from [redistricting data hub](https://redistrictingdatahub.org/) in a simplified format. An API key from covid act now is required to get the data.

In [1]:
import glob
import requests

import pandas as pd
import numpy as np

In [2]:

response_API = requests.get('https://api.covidactnow.org/v2/counties.timeseries.csv?****ADD YOUR API KEY HERE****')
file = open('covid_data.csv', "w")
file.write(response_API.text)
file.close()

covid_df = pd.read_csv('covid_data.csv')

In [3]:
covid_df.head()

,date,country,state,county,fips,lat,long,locationId,actuals.cases,actuals.deaths,...,unused3,unused4,metrics.icuCapacityRatio,riskLevels.overall,metrics.vaccinationsInitiatedRatio,metrics.vaccinationsCompletedRatio,actuals.newDeaths,actuals.vaccinesAdministered,riskLevels.caseDensity,cdcTransmissionLevel
0,2020-04-09,US,AK,Aleutians East Borough,2013,NaN,NaN,iso1:us#iso2:us-ak#fips:02013,NaN,NaN,...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,0
1,2020-04-10,US,AK,Aleutians East Borough,2013,NaN,NaN,iso1:us#iso2:us-ak#fips:02013,NaN,NaN,...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,0
2,2020-04-11,US,AK,Aleutians East Borough,2013,NaN,NaN,iso1:us#iso2:us-ak#fips:02013,NaN,NaN,...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,0
3,2020-04-12,US,AK,Aleutians East Borough,2013,NaN,NaN,iso1:us#iso2:us-ak#fips:02013,NaN,NaN,...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,0
4,2020-04-13,US,AK,Aleutians East Borough,2013,NaN,NaN,iso1:us#iso2:us-ak#fips:02013,NaN,NaN,...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,0

In [4]:
covid_df.info(show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2089455 entries, 0 to 2089454
Data columns (total 41 columns):
 #   Column                                  Non-Null Count    Dtype
---  ------                                  --------------    -----
 0   date                                    2089455 non-null  object
 1   country                                 2089455 non-null  object
 2   state                                   2089455 non-null  object
 3   county                                  2089455 non-null  object
 4   fips                                    2089455 non-null  int64
 5   lat                                     0 non-null        float64
 6   long                                    0 non-null        float64
 7   locationId                              2089455 non-null  object
 8   actuals.cases                           2046731 non-null  float64
 9   actuals.deaths                          2001090 non-null  float64
 10  actuals.positiveTests                   657 non-null      float64
 11  actuals.negativeTests                   660 non-null      float64
 12  actuals.contactTracers                  599 non-null      float64
 13  actuals.hospitalBeds.capacity           209482 non-null   float64
 14  actuals.hospitalBeds.currentUsageTotal  206415 non-null   float64
 15  actuals.hospitalBeds.currentUsageCovid  147981 non-null   float64
 16  unused1                                 0 non-null        float64
 17  actuals.icuBeds.capacity                134453 non-null   float64
 18  actuals.icuBeds.currentUsageTotal       121475 non-null   float64
 19  actuals.icuBeds.currentUsageCovid       97914 non-null    float64
 20  unused2                                 0 non-null        float64
 21  actuals.newCases                        2027196 non-null  float64
 22  actuals.vaccinesDistributed             2146 non-null     float64
 23  actuals.vaccinationsInitiated           1026878 non-null  float64
 24  actuals.vaccinationsCompleted           1014757 non-null  float64
 25  metrics.testPositivityRatio             1909062 non-null  float64
 26  metrics.testPositivityRatioDetails      0 non-null        float64
 27  metrics.caseDensity                     2070690 non-null  float64
 28  metrics.contactTracerCapacityRatio      596 non-null      float64
 29  metrics.infectionRate                   1918854 non-null  float64
 30  metrics.infectionRateCI90               1918854 non-null  float64
 31  unused3                                 0 non-null        float64
 32  unused4                                 0 non-null        float64
 33  metrics.icuCapacityRatio                120610 non-null   float64
 34  riskLevels.overall                      2089455 non-null  int64
 35  metrics.vaccinationsInitiatedRatio      1022412 non-null  float64
 36  metrics.vaccinationsCompletedRatio      1009838 non-null  float64
 37  actuals.newDeaths                       1991382 non-null  float64
 38  actuals.vaccinesAdministered            296886 non-null   float64
 39  riskLevels.caseDensity                  2089455 non-null  int64
 40  cdcTransmissionLevel                    2089455 non-null  int64
dtypes: float64(32), int64(4), object(5)
memory usage: 653.6+ MB

In [5]:
use_columns = ['date', 'country', 'state', 'county', 'locationId', 'actuals.newCases', 'actuals.newDeaths', 'actuals.cases', 'actuals.deaths', 'actuals.icuBeds.currentUsageCovid', 'actuals.icuBeds.currentUsageTotal', 'actuals.icuBeds.capacity', 'actuals.vaccinationsInitiated', 'actuals.vaccinationsCompleted', ]
cleaned_covid_df = covid_df[use_columns]

In [6]:
file_list = glob.glob('census_data_by_county/**/*.csv')
df_list = []
for file in file_list:
    df = pd.read_csv(file)
    df_list.append(df)
df = pd.DataFrame()
census_df = df.append([df for df in df_list], ignore_index=True)

In [7]:
print(len(census_df.columns))

332

In [8]:
print(census_df.columns[:100])
print(census_df.columns[100:200])
print(census_df.columns[200:300])
print(census_df.columns[300])

Index(['FILEID', 'STUSAB', 'SUMLEV', 'GEOVAR', 'GEOCOMP', 'CHARITER',
       'LOGRECNO', 'GEOID', 'GEOCODE', 'REGION', 'DIVISION', 'STATE',
       'STATENS', 'COUNTY', 'COUNTYCC', 'COUNTYNS', 'CBSA', 'MEMI', 'CSA',
       'METDIV', 'AREALAND', 'AREAWATR', 'BASENAME', 'NAME', 'FUNCSTAT',
       'POP100', 'HU100', 'INTPTLAT', 'INTPTLON', 'LSADC', 'GEOID20',
       'P0010001', 'P0010002', 'P0010003', 'P0010004', 'P0010005', 'P0010006',
       'P0010007', 'P0010008', 'P0010009', 'P0010010', 'P0010011', 'P0010012',
       'P0010013', 'P0010014', 'P0010015', 'P0010016', 'P0010017', 'P0010018',
       'P0010019', 'P0010020', 'P0010021', 'P0010022', 'P0010023', 'P0010024',
       'P0010025', 'P0010026', 'P0010027', 'P0010028', 'P0010029', 'P0010030',
       'P0010031', 'P0010032', 'P0010033', 'P0010034', 'P0010035', 'P0010036',
       'P0010037', 'P0010038', 'P0010039', 'P0010040', 'P0010041', 'P0010042',
       'P0010043', 'P0010044', 'P0010045', 'P0010046', 'P0010047', 'P0010048',
       'P0010049', 'P0010050', 'P0010051', 'P0010052', 'P0010053', 'P0010054',
       'P0010055', 'P0010056', 'P0010057', 'P0010058', 'P0010059', 'P0010060',
       'P0010061', 'P0010062', 'P0010063', 'P0010064', 'P0010065', 'P0010066',
       'P0010067', 'P0010068', 'P0010069'],
      dtype='object')
Index(['P0010070', 'P0010071', 'P0020001', 'P0020002', 'P0020003', 'P0020004',
       'P0020005', 'P0020006', 'P0020007', 'P0020008', 'P0020009', 'P0020010',
       'P0020011', 'P0020012', 'P0020013', 'P0020014', 'P0020015', 'P0020016',
       'P0020017', 'P0020018', 'P0020019', 'P0020020', 'P0020021', 'P0020022',
       'P0020023', 'P0020024', 'P0020025', 'P0020026', 'P0020027', 'P0020028',
       'P0020029', 'P0020030', 'P0020031', 'P0020032', 'P0020033', 'P0020034',
       'P0020035', 'P0020036', 'P0020037', 'P0020038', 'P0020039', 'P0020040',
       'P0020041', 'P0020042', 'P0020043', 'P0020044', 'P0020045', 'P0020046',
       'P0020047', 'P0020048', 'P0020049', 'P0020050', 'P0020051', 'P0020052',
       'P0020053', 'P0020054', 'P0020055', 'P0020056', 'P0020057', 'P0020058',
       'P0020059', 'P0020060', 'P0020061', 'P0020062', 'P0020063', 'P0020064',
       'P0020065', 'P0020066', 'P0020067', 'P0020068', 'P0020069', 'P0020070',
       'P0020071', 'P0020072', 'P0020073', 'P0030001', 'P0030002', 'P0030003',
       'P0030004', 'P0030005', 'P0030006', 'P0030007', 'P0030008', 'P0030009',
       'P0030010', 'P0030011', 'P0030012', 'P0030013', 'P0030014', 'P0030015',
       'P0030016', 'P0030017', 'P0030018', 'P0030019', 'P0030020', 'P0030021',
       'P0030022', 'P0030023', 'P0030024', 'P0030025'],
      dtype='object')
Index(['P0030026', 'P0030027', 'P0030028', 'P0030029', 'P0030030', 'P0030031',
       'P0030032', 'P0030033', 'P0030034', 'P0030035', 'P0030036', 'P0030037',
       'P0030038', 'P0030039', 'P0030040', 'P0030041', 'P0030042', 'P0030043',
       'P0030044', 'P0030045', 'P0030046', 'P0030047', 'P0030048', 'P0030049',
       'P0030050', 'P0030051', 'P0030052', 'P0030053', 'P0030054', 'P0030055',
       'P0030056', 'P0030057', 'P0030058', 'P0030059', 'P0030060', 'P0030061',
       'P0030062', 'P0030063', 'P0030064', 'P0030065', 'P0030066', 'P0030067',
       'P0030068', 'P0030069', 'P0030070', 'P0030071', 'P0040001', 'P0040002',
       'P0040003', 'P0040004', 'P0040005', 'P0040006', 'P0040007', 'P0040008',
       'P0040009', 'P0040010', 'P0040011', 'P0040012', 'P0040013', 'P0040014',
       'P0040015', 'P0040016', 'P0040017', 'P0040018', 'P0040019', 'P0040020',
       'P0040021', 'P0040022', 'P0040023', 'P0040024', 'P0040025', 'P0040026',
       'P0040027', 'P0040028', 'P0040029', 'P0040030', 'P0040031', 'P0040032',
       'P0040033', 'P0040034', 'P0040035', 'P0040036', 'P0040037', 'P0040038',
       'P0040039', 'P0040040', 'P0040041', 'P0040042', 'P0040043', 'P0040044',
       'P0040045', 'P0040046', 'P0040047', 'P0040048', 'P0040049', 'P0040050',
       'P0040051', 'P0040052', 'P0040053', 'P0040054'],
      dtype='object')
P0040055

In [9]:
fields = ['STUSAB','NAME','POP100','AREALAND']
pop_by_county_df =  census_df[fields]
pop_by_county_df.loc[len(pop_by_county_df.index)] = ['DC', 'District of Columbia', 689545, 177000000] #Inserted manually because it wasn't available on redistrictingdatahub

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:723: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value, self.name)

In [10]:
list_temp = []
for line in pop_by_county_df['NAME']:
    list_temp.append(np.sum(cleaned_covid_df['county'] == line))

print(np.sum(np.array(list_temp) == 0))

missing_index = np.where(np.array(list_temp) == 0)
print('missing counties:')
print(pop_by_county_df.iloc[missing_index])

2
missing counties:
  STUSAB                      NAME  POP100     AREALAND
5     AK       Chugach Census Area    7102  24682168359
6     AK  Copper River Census Area    2617  63952335592

In [11]:
cleaned_covid_df['county_pop'] = np.nan
cleaned_covid_df['land_area'] = np.nan
for row in pop_by_county_df.index:
    state_filter = (cleaned_covid_df['state'] == pop_by_county_df.iloc[row]['STUSAB'])
    county_filter = (cleaned_covid_df['county'] == pop_by_county_df.iloc[row]['NAME'])
    pop_temp = pop_by_county_df.iloc[row]['POP100']
    area_temp = pop_by_county_df.iloc[row]['AREALAND']

    filter_temp = state_filter&county_filter

    cleaned_covid_df.loc[filter_temp, 'county_pop'] = pop_temp
    cleaned_covid_df.loc[filter_temp, 'land_area'] = area_temp

C:\Users\cwpet\AppData\Local\Temp/ipykernel_11836/1077820956.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_covid_df['county_pop'] = np.nan
C:\Users\cwpet\AppData\Local\Temp/ipykernel_11836/1077820956.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_covid_df['land_area'] = np.nan
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [12]:
name_map = {'actuals.newCases': 'new_cases', 'actuals.newDeaths': 'new_deaths', 'actuals.cases': 'total_cases', 'actuals.deaths': 'total_deaths',
 'actuals.icuBeds.currentUsageCovid': 'icu_beds_used_covid', 'actuals.icuBeds.currentUsageTotal': 'icu_beds_used_total',
  'actuals.icuBeds.capacity': 'icu_beds_total', 'actuals.vaccinationsInitiated': 'vax_initiated', 'actuals.vaccinationsCompleted': 'vax_completed'}

cleaned_covid_df.rename(columns=name_map, inplace=True)
cleaned_covid_df.tail()

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

,date,country,state,county,locationId,new_cases,new_deaths,total_cases,total_deaths,icu_beds_used_covid,icu_beds_used_total,icu_beds_total,vax_initiated,vax_completed,county_pop,land_area
2089450,2021-12-25,US,WY,Weston County,iso1:us#iso2:us-wy#fips:56045,0.0,0.0,1246.0,14.0,NaN,NaN,NaN,2663.0,2368.0,6838.0,6.210804e+09
2089451,2021-12-26,US,WY,Weston County,iso1:us#iso2:us-wy#fips:56045,0.0,0.0,1246.0,14.0,NaN,NaN,NaN,2663.0,2368.0,6838.0,6.210804e+09
2089452,2021-12-27,US,WY,Weston County,iso1:us#iso2:us-wy#fips:56045,1.0,0.0,1247.0,14.0,NaN,NaN,NaN,2663.0,2368.0,6838.0,6.210804e+09
2089453,2021-12-28,US,WY,Weston County,iso1:us#iso2:us-wy#fips:56045,2.0,0.0,1249.0,14.0,NaN,NaN,NaN,2664.0,2369.0,6838.0,6.210804e+09
2089454,2021-12-29,US,WY,Weston County,iso1:us#iso2:us-wy#fips:56045,3.0,0.0,1252.0,14.0,NaN,NaN,NaN,2669.0,2372.0,6838.0,6.210804e+09

In [13]:
cleaned_covid_df.to_csv('covid_data_withpop.csv', index=False)